<%@ Page Title="Address" Language="C#" AutoEventWireup="true" MasterPageFile="~/Web_Forms/Site.Master" CodeBehind="Address.aspx.cs" Inherits="VotingSytem.Webforms.Address" %>

<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">
    <div class="container ma-12">
        <div>
            <h2>Address
            </h2>
        </div>
        <div class="form-group mb-2">
            <asp:Label ID="addressIdLabel" runat="server" Text="Address ID"></asp:Label>
            <asp:TextBox ID="addressIdTextbox" runat="server" CssClass="form-control"></asp:TextBox>
            <asp:RequiredFieldValidator ID="RequiredFieldValidator1" runat="server" Display="Dynamic" ErrorMessage="This Field is Required!" ControlToValidate="addressIdTextbox" ForeColor="#FF6666"></asp:RequiredFieldValidator>
        </div>

        <div class="form-group mb-2">
            <asp:Label ID="addressNameLabel" runat="server" Text="Address Name"></asp:Label>
            <asp:TextBox ID="addressNameTextbox" runat="server" CssClass="form-control"></asp:TextBox>
            <asp:RequiredFieldValidator ID="RequiredFieldValidator2" runat="server" Display="Dynamic" ErrorMessage="This Field is Required!" ControlToValidate="addressNameTextbox" ForeColor="#FF6666"></asp:RequiredFieldValidator>
        </div>

        <div class="form-group mb-2">
            <asp:Button ID="createAddressButton" runat="server" Text="Add" CssClass="btn btn-primary" OnClick="CreateAddressBtn_Click" />
            <asp:Button ID="updateAddressButton" runat="server" Text="Update" CssClass="btn btn-primary" OnClick="UpdateAddressBtn_Click" />
        </div>
        <div class="form-group mb-2">
            
        </div>
        <div>
            <asp:GridView ID="AddressGV" runat="server" Height="148px" Width="1020px" CssClass="table" EmptyDataText="No Record Has Been Added!" OnRowDeleting="DeleteAddress" OnRowEditing="EditAddress" AutoGenerateColumns="False" BackColor="White" BorderColor="#DEDFDE" BorderStyle="None" BorderWidth="1px" CellPadding="4" ForeColor="Black" GridLines="Vertical" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataKeyNames="ADDRESS_ID">
                <AlternatingRowStyle BackColor="White" />
                <Columns>
                    <asp:BoundField DataField="ADDRESS_ID" HeaderText="ADDRESS_ID" ReadOnly="True" SortExpression="ADDRESS_ID" />
                    <asp:BoundField DataField="ADDRESS_NAME" HeaderText="ADDRESS_NAME" SortExpression="ADDRESS_NAME" />
                </Columns>
                <FooterStyle BackColor="#CCCC99" />
                <HeaderStyle BackColor="#6B696B" Font-Bold="True" ForeColor="White" />
                <PagerStyle BackColor="#F7F7DE" ForeColor="Black" HorizontalAlign="Right" />
                <RowStyle BackColor="#F7F7DE" />
                <SelectedRowStyle BackColor="#CE5D5A" Font-Bold="True" ForeColor="White" />
                <SortedAscendingCellStyle BackColor="#FBFBF2" />
                <SortedAscendingHeaderStyle BackColor="#848384" />
                <SortedDescendingCellStyle BackColor="#EAEAD3" />
                <SortedDescendingHeaderStyle BackColor="#575357" />
            </asp:GridView>


    </div>
</asp:Content>
