<%@ Page Title="Department" Language="C#" AutoEventWireup="true" MasterPageFile="~/Web_Forms/Site.Master" CodeBehind="Department.aspx.cs" Inherits="VotingSytem.Webforms.Department" %>

<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">
    <div class="container ma-12">
        <div>
            <h2>Department
            </h2>
        </div>
        <div class="form-group mb-2">
            <asp:Label ID="deptIdLabel" runat="server" Text="Department ID"></asp:Label>
            <asp:TextBox ID="deptIdTextbox" runat="server" CssClass="form-control"></asp:TextBox>
            <asp:RequiredFieldValidator ID="RequiredFieldValidator1" runat="server" Display="Dynamic" ErrorMessage="This Field is Required!" ControlToValidate="deptIdTextbox" ForeColor="#FF6666"></asp:RequiredFieldValidator>
        </div>

        <div class="form-group mb-2">
            <asp:Label ID="deptNameLabel" runat="server" Text="Department Name"></asp:Label>
            <asp:TextBox ID="deptNameTextbox" runat="server" CssClass="form-control"></asp:TextBox>
            <asp:RequiredFieldValidator ID="RequiredFieldValidator2" runat="server" Display="Dynamic" ErrorMessage="This Field is Required!" ControlToValidate="deptNameTextbox" ForeColor="#FF6666"></asp:RequiredFieldValidator>
        </div>

        <div class="form-group mb-2">
            <asp:Button ID="createDeptButton" runat="server" Text="Add" CssClass="btn btn-primary" OnClick="CreateDeptBtn_Click" />
            <asp:Button ID="updateDeptButton" runat="server" Text="Update" CssClass="btn btn-primary" OnClick="UpdateDeptBtn_Click" />
            <asp:Button ID="clearFormButton" runat="server" Text="Clear" CssClass="btn btn-primary" OnClick="ClearBtn_Click" />
        </div>
        <div class="form-group mb-2">
            
        </div>
        <div>
            <asp:GridView ID="DepartmentGV" runat="server" Height="148px" Width="1020px" CssClass="table" EmptyDataText="No Record Has Been Added!" OnRowDeleting="DeleteDepartment" OnRowEditing="EditDepartment" AutoGenerateColumns="False" BackColor="White" BorderColor="#DEDFDE" BorderStyle="None" BorderWidth="1px" CellPadding="4" ForeColor="Black" GridLines="Vertical" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataKeyNames="DEPARTMENT_ID">
                <AlternatingRowStyle BackColor="White" />
                <Columns>
                    <asp:BoundField DataField="DEPARTMENT_ID" HeaderText="DEPARTMENT_ID" ReadOnly="True" SortExpression="DEPARTMENT_ID" />
                    <asp:BoundField DataField="DEPARTMENT_NAME" HeaderText="DEPARTMENT_NAME" SortExpression="DEPARTMENT_NAME" />
                </Columns>
                <FooterStyle BackColor="#CCCC99" />
                <HeaderStyle BackColor="#6B696B" Font-Bold="True" ForeColor="White" />
                <PagerStyle BackColor="#F7F7DE" ForeColor="Black" HorizontalAlign="Right" />
                <RowStyle BackColor="#F7F7DE" />
                <SelectedRowStyle BackColor="#CE5D5A" Font-Bold="True" ForeColor="White" />
                <SortedAscendingCellStyle BackColor="#FBFBF2" />
                <SortedAscendingHeaderStyle BackColor="#848384" />
                <SortedDescendingCellStyle BackColor="#EAEAD3" />
                <SortedDescendingHeaderStyle BackColor="#575357" />
            </asp:GridView>

            <asp:SqlDataSource ID="DepartmentDataSource" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString %>" ProviderName="<%$ ConnectionStrings:ConnectionString.ProviderName %>" SelectCommand="SELECT * FROM &quot;DEPARTMENT&quot;"></asp:SqlDataSource>

            <asp:SqlDataSource ID="VotingDataSource" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString %>" ProviderName="<%$ ConnectionStrings:ConnectionString.ProviderName %>" SelectCommand="SELECT * FROM &quot;DEPARTMENT&quot;"></asp:SqlDataSource>

        </div>

    </div>
</asp:Content>
