<%@ Page Title="Employee" Language="C#" AutoEventWireup="true" MasterPageFile="~/Web_Forms/Site.Master" CodeBehind="Employee.aspx.cs" Inherits="VotingSytem.Webforms.Employee" %>

<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">
    <div class="container ma-12">
        <div>
            <h2>Employee
            </h2>
        </div>
        <div class="form-group mb-2">
            <asp:Label ID="Label1" runat="server" Text="Name"></asp:Label>
            <asp:TextBox ID="employeeNameTextbox" runat="server" CssClass="form-control"></asp:TextBox>
            <asp:RequiredFieldValidator ID="RequiredFieldValidator1" runat="server" Display="Dynamic" ErrorMessage="This Field is Required!" ControlToValidate="employeeNameTextbox" ForeColor="#FF6666"></asp:RequiredFieldValidator>
        </div>

        <div class="form-group mb-2">
            <asp:Label ID="dateOfBirthLabel" runat="server" Text="Date of Birth"></asp:Label>
            <asp:TextBox ID="dateOfBirthTextbox" runat="server" CssClass="form-control"></asp:TextBox>
            <asp:RequiredFieldValidator ID="RequiredFieldValidator2" runat="server" Display="Dynamic" ErrorMessage="This Field is Required!" ControlToValidate="dateOfBirthTextbox" ForeColor="#FF6666"></asp:RequiredFieldValidator>
        </div>
        <div class="form-group mb-2">
            <asp:Label ID="contactLabel" runat="server" Text="Contact"></asp:Label>
            <asp:TextBox ID="contactTextbox" runat="server" CssClass="form-control"></asp:TextBox>
            <asp:RequiredFieldValidator ID="RequiredFieldValidator4" runat="server" Display="Dynamic" ErrorMessage="This Field is Required!" ControlToValidate="contactTextbox" ForeColor="#FF6666"></asp:RequiredFieldValidator>
        </div>

        <div class="form-group mb-2">
            <asp:Button ID="createEmployeeButton" runat="server" Text="Add" CssClass="btn btn-primary" OnClick="CreateEmployeeBtn_Click" />
            <asp:Button ID="updateEmployeeButton" runat="server" Text="Update" CssClass="btn btn-primary" OnClick="UpdateEmployeeBtn_Click" />
            <asp:Button ID="clearFormButton" runat="server" Text="Clear" CssClass="btn btn-primary" OnClick="ClearBtn_Click" />
        </div>
        <div class="form-group mb-2">
        </div>
        <div>
            <asp:GridView ID="EmployeeGV" runat="server" Height="148px" Width="1000px" CssClass="table" EmptyDataText="No Record Has Been Added!" OnRowDeleting="DeleteEmployee" OnRowEditing="EditRecord" AutoGenerateColumns="False" DataKeyNames="EMPLOYEE_ID" BackColor="White" BorderColor="#DEDFDE" BorderStyle="None" BorderWidth="1px" CellPadding="4" ForeColor="Black" GridLines="Vertical" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True">
                <AlternatingRowStyle BackColor="White" />
                <Columns>
                    <asp:BoundField DataField="EMPLOYEE_ID" HeaderText="EMPLOYEE_ID" ReadOnly="True" SortExpression="EMPLOYEE_ID" />
                    <asp:BoundField DataField="EMPLOYEE_NAME" HeaderText="EMPLOYEE_NAME" SortExpression="EMPLOYEE_NAME" />
                    <asp:BoundField DataField="DATE_OF_BIRTH" HeaderText="DATE_OF_BIRTH" SortExpression="DATE_OF_BIRTH" DataFormatString="{0:dd-MM-yyyy}" />
                    <asp:BoundField DataField="CONTACT" HeaderText="CONTACT" SortExpression="CONTACT" />
                </Columns>
                <FooterStyle BackColor="#CCCC99" />
                <HeaderStyle BackColor="#6B696B" Font-Bold="True" ForeColor="White" />
                <PagerStyle BackColor="#F7F7DE" ForeColor="Black" HorizontalAlign="Right" />
                <RowStyle BackColor="#f7f7f7" />
                <SelectedRowStyle BackColor="#CE5D5A" Font-Bold="True" ForeColor="White" />
                <SortedAscendingCellStyle BackColor="#FBFBF2" />
                <SortedAscendingHeaderStyle BackColor="#848384" />
                <SortedDescendingCellStyle BackColor="#EAEAD3" />
                <SortedDescendingHeaderStyle BackColor="#575357" />
            </asp:GridView>

            <asp:SqlDataSource ID="VotingDataSource" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString %>" ProviderName="<%$ ConnectionStrings:ConnectionString.ProviderName %>" SelectCommand="SELECT * FROM &quot;EMPLOYEE&quot;"></asp:SqlDataSource>

            <asp:SqlDataSource ID="CWDataSource" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString %>" ProviderName="<%$ ConnectionStrings:ConnectionString.ProviderName %>" SelectCommand="SELECT * FROM &quot;EMPLOYEE&quot;"></asp:SqlDataSource>

        </div>
        <div id="errorModal" class="modal fade" role="dialog">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h4 class="modal-title">Error</h4>
                    </div>
                    <div class="modal-body">
                        <asp:Label ID="errorLabel" runat="server"></asp:Label>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    </div>
                </div>
            </div>
        </div>

    </div>
</asp:Content>
