<%@ Page Title="Job" Language="C#" AutoEventWireup="true" MasterPageFile="~/Web_Forms/Site.Master" CodeBehind="Job.aspx.cs" Inherits="VotingSytem.Webforms.Job" %>

<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">
    <div class="container ma-12">
        <div>
            <h2>Job
            </h2>
        </div>
        <div class="form-group mb-2">
            <asp:Label ID="jobIdLabel" runat="server" Text="Job ID"></asp:Label>
            <asp:TextBox ID="jobIdTextbox" runat="server" CssClass="form-control"></asp:TextBox>
            <asp:RequiredFieldValidator ID="RequiredFieldValidator1" runat="server" Display="Dynamic" ErrorMessage="This Field is Required!" ControlToValidate="jobIdTextbox" ForeColor="#FF6666"></asp:RequiredFieldValidator>
        </div>

        <div class="form-group mb-2">
            <asp:Label ID="jobNameLabel" runat="server" Text="Job Name"></asp:Label>
            <asp:TextBox ID="jobNameTextbox" runat="server" CssClass="form-control"></asp:TextBox>
            <asp:RequiredFieldValidator ID="RequiredFieldValidator2" runat="server" Display="Dynamic" ErrorMessage="This Field is Required!" ControlToValidate="jobNameTextbox" ForeColor="#FF6666"></asp:RequiredFieldValidator>
        </div>

         <div class="form-group mb-2">
            <asp:Label ID="RoleLabel" runat="server" Text="Role"></asp:Label>
             <asp:DropDownList ID="RoleDropDown" runat="server"></asp:DropDownList>
            <asp:RequiredFieldValidator ID="RequiredFieldValidator3" runat="server" Display="Dynamic" ErrorMessage="This Field is Required!" ControlToValidate="RoleDropDown" ForeColor="#FF6666"></asp:RequiredFieldValidator>
        </div>

        <div class="form-group mb-2">
            <asp:Button ID="createJobButton" runat="server" Text="Add" CssClass="btn btn-primary" OnClick="CreateJobBtn_Click" />
            <asp:Button ID="updateJobButton" runat="server" Text="Update" CssClass="btn btn-primary" OnClick="UpdateJobBtn_Click" />
            <asp:Button ID="clearFormButton" runat="server" Text="Clear" CssClass="btn btn-primary" OnClick="ClearBtn_Click" />
        </div>
        <div class="form-group mb-2">
            
        </div>
        <div>
            <asp:GridView ID="JobGV" runat="server" Height="148px" Width="938px" CssClass="table" EmptyDataText="No Record Has Been Added!" OnRowDeleting="DeleteJob" OnRowEditing="EditJob" AutoGenerateColumns="False" BackColor="White" BorderColor="#DEDFDE" BorderStyle="None" BorderWidth="1px" CellPadding="4" ForeColor="Black" GridLines="Vertical" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataKeyNames="JOB_ID">
                <AlternatingRowStyle BackColor="White" />
                <Columns>
                    <asp:BoundField DataField="JOB_ID" HeaderText="JOB_ID" ReadOnly="True" SortExpression="JOB_ID" />
                    <asp:BoundField DataField="JOB_NAME" HeaderText="JOB_NAME" SortExpression="JOB_NAME" />
                    <asp:BoundField DataField="ROLE_NAME" HeaderText="ROLE_NAME" SortExpression="ROLE_NAME" />
                </Columns>
                <FooterStyle BackColor="#CCCC99" />
                <HeaderStyle BackColor="#6B696B" Font-Bold="True" ForeColor="White" />
                <PagerStyle BackColor="#F7F7DE" ForeColor="Black" HorizontalAlign="Right" />
                <RowStyle BackColor="#F7F7DE" />
                <SelectedRowStyle BackColor="#CE5D5A" Font-Bold="True" ForeColor="White" />
                <SortedAscendingCellStyle BackColor="#FBFBF2" />
                <SortedAscendingHeaderStyle BackColor="#848384" />
                <SortedDescendingCellStyle BackColor="#EAEAD3" />
                <SortedDescendingHeaderStyle BackColor="#575357" />
            </asp:GridView>

           

            <asp:SqlDataSource ID="JobDataSource" runat="server"></asp:SqlDataSource>

           

        </div>

    </div>
</asp:Content>
