<%@ Page Title="Role" Language="C#" AutoEventWireup="true" MasterPageFile="~/Web_Forms/Site.Master" CodeBehind="Role.aspx.cs" Inherits="VotingSytem.Webforms.Role" %>

<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">
    <div class="container ma-12">
        <div>
            <h2>Role
            </h2>
        </div>
        <div class="form-group mb-2">
            <asp:Label ID="roleIdLabel" runat="server" Text="Role ID"></asp:Label>
            <asp:TextBox ID="roleIdTextbox" runat="server" CssClass="form-control"></asp:TextBox>
            <asp:RequiredFieldValidator ID="RequiredFieldValidator1" runat="server" Display="Dynamic" ErrorMessage="This Field is Required!" ControlToValidate="roleIdTextbox" ForeColor="#FF6666"></asp:RequiredFieldValidator>
        </div>

        <div class="form-group mb-2">
            <asp:Label ID="roleNameLabel" runat="server" Text="Role Name"></asp:Label>
            <asp:TextBox ID="roleNameTextbox" runat="server" CssClass="form-control"></asp:TextBox>
            <asp:RequiredFieldValidator ID="RequiredFieldValidator2" runat="server" Display="Dynamic" ErrorMessage="This Field is Required!" ControlToValidate="roleNameTextbox" ForeColor="#FF6666"></asp:RequiredFieldValidator>
        </div>

        <div class="form-group mb-2">
            <asp:Button ID="createRoleButton" runat="server" Text="Add" CssClass="btn btn-primary" OnClick="CreateRoleBtn_Click" />
            <asp:Button ID="updateRoleButton" runat="server" Text="Update" CssClass="btn btn-primary" OnClick="UpdateRoleBtn_Click" />
            <asp:Button ID="clearFormButton" runat="server" Text="Clear" CssClass="btn btn-primary" OnClick="ClearBtn_Click" />
        </div>
        <div class="form-group mb-2">
            
        </div>
        <div>
            <asp:GridView ID="RoleGV" runat="server" Height="148px" Width="1020px" CssClass="table" EmptyDataText="No Record Has Been Added!" OnRowDeleting="DeleteRole" OnRowEditing="EditRole" AutoGenerateColumns="False" BackColor="White" BorderColor="#DEDFDE" BorderStyle="None" BorderWidth="1px" CellPadding="4" ForeColor="Black" GridLines="Vertical" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataKeyNames="ROLE_ID">
                <AlternatingRowStyle BackColor="White" />
                <Columns>
                    <asp:BoundField DataField="ROLE_ID" HeaderText="ROLE_ID" ReadOnly="True" SortExpression="ROLE_ID" />
                    <asp:BoundField DataField="ROLE_NAME" HeaderText="ROLE_NAME" SortExpression="ROLE_NAME" />
                </Columns>
                <FooterStyle BackColor="#CCCC99" />
                <HeaderStyle BackColor="#6B696B" Font-Bold="True" ForeColor="White" />
                <PagerStyle BackColor="#F7F7DE" ForeColor="Black" HorizontalAlign="Right" />
                <RowStyle BackColor="#f7f7f7" />
                <SelectedRowStyle BackColor="#CE5D5A" Font-Bold="True" ForeColor="White" />
                <SortedAscendingCellStyle BackColor="#FBFBF2" />
                <SortedAscendingHeaderStyle BackColor="#848384" />
                <SortedDescendingCellStyle BackColor="#EAEAD3" />
                <SortedDescendingHeaderStyle BackColor="#575357" />
            </asp:GridView>


    </div>
</asp:Content>
